OAK-11078: Remove usage of Guava checkArgument
apache/jackrabbit-oak pull request #1687
Opened 2024-09-04 17:31 UTC by reschke

2024-09-06 08:37 UTC, mbaedke requested changes

2024-09-06 08:37 UTC, mbaedke commented on oak-core/src/main/java/org/apache/jackrabbit/oak/plugins/index/AsyncIndexUpdate.java
> +        Validate.isTrue(asyncName.endsWith("async"), "async name [%s] does not confirm to naming pattern of ending with 'async'",
s/confirm/conform

2024-09-06 08:37 UTC, mbaedke commented on oak-store-document/src/main/java/org/apache/jackrabbit/oak/plugins/document/JournalEntry.java
> +            Validate.isTrue(!name.contains("/"),
Does "{}" even work in a format string?

2024-09-06 08:38 UTC, reschke commented on oak-store-document/src/main/java/org/apache/jackrabbit/oak/plugins/document/JournalEntry.java
> +            Validate.isTrue(!name.contains("/"),
No, according to the documentation.

2024-09-10 05:14 UTC, rishabhdaim approved these changes

2024-10-14 15:26 UTC, closed without merging