OAK-9447: Upgrade Mongo java driver to 5.2
apache/jackrabbit-oak pull request #1789
Opened 2024-10-14 09:09 UTC by reschke

2024-10-14 10:39 UTC, rishabhdaim requested changes

2024-10-14 10:39 UTC, rishabhdaim commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/DocumentStoreIndexerBase.java
> +            return mongoConnection.getDatabase().getCollection("nodes").countDocuments();
```suggestion
            return mongoConnection.getDatabase().getCollection("nodes").estimatedDocumentCount();
```

`countDcuments` is very slow. I would use `estimatedDocumentCount` for faster results.

See https://www.mongodb.com/community/forums/t/countdocuments-is-extremly-slow/207357

2024-10-14 10:39 UTC, rishabhdaim commented on oak-store-document/pom.xml
> +              com.mongodb*;version="[5.0, 5.2)";resolution:=optional,
Since we are switching to `5.2.0`, shouldn't it be

```suggestion
              com.mongodb*;version="[5.2, 6)";resolution:=optional,
```

2024-10-14 10:39 UTC, rishabhdaim commented on oak-store-document/pom.xml
> +              org.bson*;version="[5.0, 5.2)";resolution:=optional,
Same as above.

2024-10-14 10:39 UTC, rishabhdaim commented on oak-store-document/src/main/java/org/apache/jackrabbit/oak/plugins/document/mongo/MongoDocumentStore.java
> -                || connection.getStatus().getReplicaSetLagEstimate() < acceptableLagMillis;
`acceptableLagMillis` should be marked as deprecated since it won't be used anymore.

2024-11-05 12:04 UTC, Joscorbe commented on oak-store-document/pom.xml
> +              org.bson*;version="[5.0, 5.2)";resolution:=optional,
Yes, definitely, or `5.3)` may be better, as sometimes they also introduce breaking changes or deprecated methods in minor versions. Example in 5.1: https://www.mongodb.com/docs/drivers/java/sync/v5.2/whats-new/#what-s-new-in-5.1 
And in 4.x it happened quite more frequently: https://www.mongodb.com/docs/drivers/java/sync/v5.2/upgrade/#version-4.8-breaking-changes

2025-01-20 06:21 UTC, closed without merging