OAK-11270 Add CONTRIBUTING file to give
apache/jackrabbit-oak pull request #1862
Opened 2024-11-13 17:46 UTC by kwin

https://jackrabbit.apache.org/oak/docs/participating.html more visibility

2024-11-13 18:04 UTC, anchela requested changes
hi @kwin , thanks a lot for adding it. i had a look how the CONTRIBUTING file looks in sling modules.

here an example:
https://github.com/apache/sling-org-apache-sling-jcr-repoinit/blob/master/CONTRIBUTING.md

i find the tone chosen the sling standard file nice.
the way it's phrased in the PR feels more like an order to me. i would suggest to shamelessly copy the version from sling and just adjust the link

2024-11-13 19:05 UTC, kwin commented
> i would suggest to shamelessly copy the version from sling and just adjust the link

Done in https://github.com/apache/jackrabbit-oak/commit/9e78470a851e16c3e75ea46e244ba3850d098936

2024-11-14 08:33 UTC, anchela approved these changes

2024-11-14 09:10 UTC, rishabhdaim approved these changes

2024-11-14 09:29 UTC, merged