OAK-11199 getSubject is supported only if a security manager is allowed
apache/jackrabbit-oak pull request #1891
Opened 2024-12-09 17:26 UTC by mbaedke

2024-12-10 08:49 UTC, reschke requested changes
a) Compat*i*bility
b) The new package in commons would need a package-info

Otherwise, looks good.

2024-12-13 11:36 UTC, reschke commented
Recommendation:

- new package commons.jdkcompat (non-public, "internal" in package-info), export in pom.xml
- name of util class more specific, like Java23Security

2024-12-13 12:35 UTC, mbaedke commented
Don't know about the name Java23Security. It's certainly not more specific :)

2024-12-13 14:17 UTC, reschke approved these changes
The changes in commons now look good.

The other parts of the PR are minimal, which is good.

I haven't tested, I assume you did, @mbaedke 

The one thing that came to mind is that if we change Java23Security to "Subject", changes would be even less intrusive. Or even "Java23Subject"?  (this is bikeshedding, ignore if you want to)

2024-12-16 10:16 UTC, reschke reviewed
And maybe we should deal with

https://sonarcloud.io/component_measures?id=org.apache.jackrabbit%3Ajackrabbit-oak&pullRequest=1891&metric=new_coverage&view=list

2024-12-16 13:19 UTC, mbaedke commented
I like Java23Subject. I wouldn't call it Subject at least for the reason that the method signatures are slightly different, which might confuse readers. Of course I tested, but will run integration tests again before merging.

2024-12-17 09:09 UTC, merged

2025-01-06 07:39 UTC, reschke commented on oak-security-spi/pom.xml
> +    <dependency>
Duplicated dependency.