OAK-11299: Missing Segments With Oak Run Segment Copy
apache/jackrabbit-oak pull request #1892
Opened 2024-12-10 09:17 UTC by lweitzendorf

2025-07-16 06:48 UTC, mreutegg commented on oak-segment-azure/src/main/java/org/apache/jackrabbit/oak/segment/azure/tool/SegmentStoreMigrator.java
> +                targetArchives.sort(String::compareTo);
Sorting lexicographically only work with up to 5 digits in the archive name.
```
data00001a.tar
data33985b.tar
data99999a.tar
```
But the archive name permits more digits up to an archive number of Integer.MAX_Value.

https://github.com/apache/jackrabbit-oak/blob/5b13b559dc9d31a20676353782abff7c96e59f13/oak-segment-tar/src/main/java/org/apache/jackrabbit/oak/segment/file/tar/TarFiles.java#L261

2025-07-16 06:56 UTC, mreutegg commented on oak-segment-azure/src/main/java/org/apache/jackrabbit/oak/segment/azure/tool/SegmentStoreMigrator.java
> +            } catch (UnsupportedOperationException e) {
I assume `UnsupportedOperationException` is caught here because the `List` returned by `targetManager.listArchives()` may be immutable. I would rather copy the returned archive names in a new `ArrayList`.

2025-07-16 06:58 UTC, mreutegg requested changes
I would also like to see unit tests that validate the changes in this PR.

2025-07-16 08:56 UTC, lweitzendorf commented on oak-segment-azure/src/main/java/org/apache/jackrabbit/oak/segment/azure/tool/SegmentStoreMigrator.java
> +            } catch (UnsupportedOperationException e) {
It's a bit odd. It returns an ArrayList, but `java.util.Arrays.ArrayList` instead of `java.util.ArrayList` and the former doesn't support any resizing operation.

2025-07-16 09:02 UTC, lweitzendorf commented on oak-segment-azure/src/main/java/org/apache/jackrabbit/oak/segment/azure/tool/SegmentStoreMigrator.java
> +            } catch (UnsupportedOperationException e) {
But more generally, yes the list may be fully immutable or some other type that doesn't allow resizing. Why copy it into an ArrayList instead of just always using subList for example?

2025-07-17 09:48 UTC, mreutegg commented on oak-segment-azure/src/main/java/org/apache/jackrabbit/oak/segment/azure/tool/SegmentStoreMigrator.java
> +            } catch (UnsupportedOperationException e) {
> But more generally, yes the list may be fully immutable or some other type that doesn't allow resizing. Why copy it into an ArrayList instead of just always using subList for example?

Getting a sub list from an immutable list should work, but SegmentStoreMigrator also sorts the list and that is not possible when the list is immutable.

2025-07-17 11:47 UTC, mreutegg commented on oak-segment-azure/src/main/java/org/apache/jackrabbit/oak/segment/azure/tool/SegmentStoreMigrator.java
> +            } catch (UnsupportedOperationException e) {
There is also similar code in `AwsSegmentStoreMigrator` that needs the same fix: https://github.com/apache/jackrabbit-oak/blob/69ee5b5034275b981943b8eec871c27def94cb24/oak-segment-aws/src/main/java/org/apache/jackrabbit/oak/segment/aws/tool/AwsSegmentStoreMigrator.java#L157-L161

2025-07-17 11:55 UTC, mreutegg commented on oak-segment-azure/src/main/java/org/apache/jackrabbit/oak/segment/azure/tool/SegmentStoreMigrator.java
> +            } catch (UnsupportedOperationException e) {
So, probably makes sense to move this logic into a utility method.

2025-07-17 14:09 UTC, lweitzendorf commented on oak-segment-azure/src/main/java/org/apache/jackrabbit/oak/segment/azure/tool/SegmentStoreMigrator.java
> +            } catch (UnsupportedOperationException e) {
They share a lot of code in general. Pulling the common logic out into a base class for both might be a good option.

2025-07-28 10:26 UTC, mreutegg commented on oak-segment-azure/src/main/java/org/apache/jackrabbit/oak/segment/azure/tool/SegmentStoreMigrator.java
> +            } catch (UnsupportedOperationException e) {
This PR is now pretty big and includes quite some refactoring. Can you please split the changes into what is necessary to fix OAK-11299 and a new issue that covers the refactoring that is not essential for OAK-11299?

2025-07-28 14:14 UTC, mreutegg commented on oak-segment-remote/src/main/java/org/apache/jackrabbit/oak/segment/remote/RemoteUtilities.java
> +    public static class ArchiveIndexComparator implements Comparator<String> {
Looks good. Though, I would not expose the inner class. You could make it private and available as a public static field of type `Comparator<String>`.
```
    public static final Comparator<String> ARCHIVE_INDEX_COMPARATOR = new ArchiveIndexComparator();
```

2025-07-28 14:15 UTC, mreutegg approved these changes

2025-07-29 11:13 UTC, merged