OAK-11311: Remove usage of Guava ImmutableList
apache/jackrabbit-oak pull request #1909
Opened 2024-12-17 09:16 UTC by reschke

Ready for review.

2024-12-17 13:14 UTC, fabriziofortino approved these changes

2024-12-18 07:00 UTC, rishabhdaim requested changes

2024-12-18 07:00 UTC, rishabhdaim commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/SimpleFlatFileUtil.java
> +        String line = entryWriter.toString(CollectionUtils.toList(elements(path)), jsonText);
don't we need to wrap this inside `Collections.unmodifiableList`?

2024-12-18 07:00 UTC, rishabhdaim commented on oak-search/src/main/java/org/apache/jackrabbit/oak/plugins/index/search/Aggregate.java
> +            List<String> pathElements = CollectionUtils.toList(PathUtils.elements(nodePath));
is this a miss or left intentionally to not use `Collections.unmodifiableList`

2024-12-18 07:00 UTC, rishabhdaim commented on oak-search/src/main/java/org/apache/jackrabbit/oak/plugins/index/search/PropertyDefinition.java
> +            return toArray(CollectionUtils.toList(elements(PathUtils.getParentPath(path))), String.class);
same as above.

2024-12-18 07:00 UTC, rishabhdaim commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(t);
need to return an immutable view.

2024-12-18 07:00 UTC, rishabhdaim commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(t);
same as above.

2024-12-18 07:00 UTC, rishabhdaim commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(Iterables.concat(Lists.transform(getConfigurations(), securityConfiguration -> securityConfiguration.getConflictHandlers())));
same as above

2024-12-18 07:00 UTC, rishabhdaim commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(t);
same here

2024-12-18 07:00 UTC, rishabhdaim commented on oak-store-document/src/main/java/org/apache/jackrabbit/oak/plugins/document/bundlor/BundlorUtils.java
> +            List<String> elements = CollectionUtils.toList(PathUtils.elements(key));
`Collections.unmodifiableList` miss or intended ?

2024-12-18 07:00 UTC, rishabhdaim commented on oak-store-document/src/main/java/org/apache/jackrabbit/oak/plugins/document/bundlor/Include.java
> +        List<String> pathElements = CollectionUtils.toList(PathUtils.elements(pattern));
Collections.unmodifiableList miss or intended ?

2024-12-18 14:33 UTC, mbaedke commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/SimpleFlatFileUtil.java
> +        String line = entryWriter.toString(CollectionUtils.toList(elements(path)), jsonText);
Well, it's only used inline and entryWriter#toString() doesn't care.

2024-12-18 14:37 UTC, mbaedke commented on oak-search/src/test/java/org/apache/jackrabbit/oak/plugins/index/search/AggregateTest.java
> +import static org.apache.jackrabbit.guava.common.collect.Iterables.toArray;
double import

2024-12-18 14:46 UTC, reschke commented
I will review all of these once I'm done with the next module.

2024-12-18 14:58 UTC, mbaedke commented on oak-store-document/src/main/java/org/apache/jackrabbit/oak/plugins/document/secondary/SecondaryStoreBuilder.java
> +import java.util.ArrayList;
Redundant?

2024-12-18 15:06 UTC, mbaedke commented on oak-store-document/src/main/java/org/apache/jackrabbit/oak/plugins/document/bundlor/Include.java
> +        List<String> pathElements = CollectionUtils.toList(PathUtils.elements(pattern));
Here it's ok imho

2024-12-18 15:11 UTC, mbaedke commented on oak-store-document/src/main/java/org/apache/jackrabbit/oak/plugins/document/bundlor/BundlorUtils.java
> +            List<String> elements = CollectionUtils.toList(PathUtils.elements(key));
Here it's clearly ok.

2024-12-18 15:13 UTC, mbaedke commented on oak-search/src/main/java/org/apache/jackrabbit/oak/plugins/index/search/PropertyDefinition.java
> +            return toArray(CollectionUtils.toList(elements(PathUtils.getParentPath(path))), String.class);
Since it's only used to create an Array from it, it's ok here.

2024-12-18 15:14 UTC, mbaedke commented on oak-search/src/main/java/org/apache/jackrabbit/oak/plugins/index/search/Aggregate.java
> +            List<String> pathElements = CollectionUtils.toList(PathUtils.elements(nodePath));
Only used locally, so it's ok.

2024-12-18 15:18 UTC, mbaedke commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(t);
It's a public method, but since nobody holds a reference to that list, I don't see a need to make it immutable.

2024-12-18 15:18 UTC, mbaedke commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(t);
Also :)

2024-12-18 15:18 UTC, mbaedke commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(Iterables.concat(Lists.transform(getConfigurations(), securityConfiguration -> securityConfiguration.getConflictHandlers())));
Also

2024-12-18 15:18 UTC, mbaedke commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(t);
Also

2024-12-18 15:19 UTC, mbaedke approved these changes

2024-12-19 01:57 UTC, rishabhdaim approved these changes

2024-12-19 11:12 UTC, reschke commented on oak-search/src/test/java/org/apache/jackrabbit/oak/plugins/index/search/AggregateTest.java
> +import static org.apache.jackrabbit.guava.common.collect.Iterables.toArray;
ack

2024-12-19 11:16 UTC, reschke commented on oak-store-document/src/main/java/org/apache/jackrabbit/oak/plugins/document/secondary/SecondaryStoreBuilder.java
> +import java.util.ArrayList;
ack

2024-12-19 11:25 UTC, reschke commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(t);
Making unmodifiable.

2024-12-19 11:25 UTC, reschke commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(t);
Making unmodifiable.

2024-12-19 11:26 UTC, reschke commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(Iterables.concat(Lists.transform(getConfigurations(), securityConfiguration -> securityConfiguration.getConflictHandlers())));
Making unmodifiable.

2024-12-19 11:27 UTC, reschke commented on oak-security-spi/src/main/java/org/apache/jackrabbit/oak/spi/security/CompositeConfiguration.java
> +        return CollectionUtils.toList(t);
Making unmodifiable.

2024-12-21 06:22 UTC, rishabhdaim requested changes

2024-12-21 06:22 UTC, rishabhdaim commented on oak-run/src/test/java/org/apache/jackrabbit/oak/plugins/document/RevisionsCommandTest.java
> +            this.args = Collections.unmodifiableList(builder);
no need for `Collections.unmodifiableList` in test class.

2024-12-21 06:22 UTC, rishabhdaim commented on oak-core/src/test/java/org/apache/jackrabbit/oak/query/SQL2OptimiseQueryTest.java
> +        expected = List.of("/test/a", "/test/b");
repeat of above line.

2024-12-21 06:22 UTC, rishabhdaim commented on oak-core/src/test/java/org/apache/jackrabbit/oak/security/authorization/composite/AbstractCompositeProviderTest.java
> +        List<AggregatedPermissionProvider> l = new ArrayList<>(List.of(
```suggestion
        List<AggregatedPermissionProvider> l = Stream.of((AggregatedPermissionProvider) config.getPermissionProvider(root, workspaceName, principals),
                getTestPermissionProvider()).collect(Collectors.toList());
```

2024-12-21 06:22 UTC, rishabhdaim commented on oak-security-spi/src/test/java/org/apache/jackrabbit/oak/spi/security/user/action/AccessControlActionTest.java
> +
please revert this.

2024-12-22 10:43 UTC, closed without merging