OAK-9576: Multithreaded download synchronization issues
apache/jackrabbit-oak pull request #383
Opened 2021-10-05 05:04 UTC by averma21

2021-10-07 10:12 UTC, thomasmueller requested changes

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/DefaultMemoryManager.java
> +        // todo - should we check and block in the beginning? This creates problem in case of download resume.
Why does it create problems?

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/DefaultMemoryManager.java
> +                        if (sufficientMemory.get()) {
sufficientMemory is AtomicBoolean. I don't see why you would want to synchronize on it. Is the problem that you want to protect against concurrent calls on checkMemory? If yes, then checkMemory should be synchronized instead.

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/StoreAndSortStrategy.java
> +            nodeStates.close();
It sounds weird that createSortedStoreFile has a side effect of closing the nodeStates. Why?

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +                memoryManager.deregisterClient(registrationID);
I wonder why do we even need a callback method from the memory manager... What about if each client (of the memory manager) just calls the memory manager when needed? That would reduce the need of synchronization.

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +                nodeStates.close();
Here again we close the nodeStates.... why here? What about having a separate close() method in this class?

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +        synchronized (this) {
We now synchronise all access to entryBatch in the caller of entryBatch. What about moving all the synchronization to entryBatch itself? That would be easier to understand in my view. Or hopefully synchronization isn't needed at all (that would even be easier).

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
>              for (NodeStateHolder h : entryBatch) {
Ah, no, here we don't synchronize on entryBatch! That's inconsistent synchronization, and can cause big problems I think. (The way around it would be to clone entryBatch... but again, I would prefer if we don't need any synchronization).

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseWithSortStrategy.java
>      private ArrayList<NodeStateHolder> entryBatch = new ArrayList<>();
Java has a synchronized list...

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseWithSortStrategy.java
> +            nodeStates.close();
Here again, closing the nodeStates as a side effect of another method... I find it weird.

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/test/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/FlatFileStoreTest.java
> +                    Map<String, Long> times = new LinkedHashMap<>(); // should be sorted in increasing order of value i.e. lastModificationTime
LinkedHashMap doesn't sort in increasing order of the key. To sort, you would need to use a TreeMap.

2021-10-07 10:12 UTC, thomasmueller commented on oak-run-commons/src/test/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/FlatFileStoreTest.java
> +        for( int i = 1; i <= 15; i++) {
Why 15?

2021-10-13 07:57 UTC, averma21 commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/StoreAndSortStrategy.java
> +            nodeStates.close();
yes, this looks weird since this class is not the owner of nodeStates. This has been done to prevent OOM for multi threaded download. We need to keep on closing the nodeStates as the download tasks keep on finishing. This is mainly for TraverseAndSortTask (tasks created for parallel download) but due to code flow same pattern had to be followed here.
We could improve this but some more refactoring would be needed.

2021-10-13 08:04 UTC, averma21 commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/StoreAndSortStrategy.java
> +            nodeStates.close();
Oh I see you mean that particular method - createSortedStoreFile. 
I will see if we can add close method as you suggested.

2021-10-13 08:05 UTC, averma21 commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +                nodeStates.close();
see https://github.com/apache/jackrabbit-oak/pull/383#discussion_r727798177

2021-10-13 08:06 UTC, averma21 commented on oak-run-commons/src/test/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/FlatFileStoreTest.java
> +                    Map<String, Long> times = new LinkedHashMap<>(); // should be sorted in increasing order of value i.e. lastModificationTime
here sorting is needed in increasing order of value.

2021-10-13 10:04 UTC, averma21 commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/DefaultMemoryManager.java
> +                        if (sufficientMemory.get()) {
As per the current code, we don't want to call checkMemory again, if sufficientMemory is already false, hence this approach.

2021-10-25 06:31 UTC, averma21 commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +                memoryManager.deregisterClient(registrationID);
As discussed, this is needed because we want the clients to tell memory manager that they have finished dumping their data so that it could set the memory low flag to false, without depending on actual garbage collection run. For implementing this synchronization, we need to list of clients which would be iterated upon to inform about memory low condition and for providing the clients the phaser/latch on which synchronization would be done.

2021-10-25 06:32 UTC, averma21 commented on oak-run-commons/src/test/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/FlatFileStoreTest.java
> +        for( int i = 1; i <= 15; i++) {
This is test class. I just increased the data in the test a bit.

2021-10-25 12:05 UTC, averma21 commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/DefaultMemoryManager.java
> +        // todo - should we check and block in the beginning? This creates problem in case of download resume.
I don't see a purpose of checking the memory during the beginning. There is nothing to do in this case. The only thing we could do is not to proceed further, but such kind of check could be added even before this stage. 

This one creates a problem during resume, in case memory is low due to previous run. It won't have any registered clients who still need to dump data (since previous run task objects would be unreachable) and checkMemory waits for clients to dump data. So the process blocks.

2021-10-25 12:25 UTC, averma21 commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +        synchronized (this) {
The synchronization is not just for entryBatch, but it couples a few things along. For example, see `memoryLow` method which is also synchronized on `this` object and works with phaser. So using a concurrent data structure for entryBatch won't be enough.

2021-10-26 07:25 UTC, fabriziofortino requested changes

2021-10-26 07:25 UTC, fabriziofortino commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/DocumentStoreIndexerBase.java
>      public DocumentStoreIndexerBase(IndexHelper indexHelper, IndexerSupport indexerSupport) throws IOException {
this should not throw IOE

2021-10-26 07:25 UTC, fabriziofortino commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/DocumentStoreIndexerBase.java
> +                    e.printStackTrace();
this should not be needed since the instruction above should print the stack trace

2021-10-26 07:25 UTC, fabriziofortino commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/FlatFileNodeStoreBuilder.java
>       */
remove import of `LastModifiedRange`

2021-10-26 07:25 UTC, fabriziofortino commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/MultithreadedTraverseWithSortStrategy.java
The link in the javadoc below should be `FlatFileNodeStoreBuilder#PROP_THREAD_POOL_SIZE`

2021-10-26 07:25 UTC, fabriziofortino commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> -    private final AtomicBoolean dumpData = new AtomicBoolean(false);
remove import of `AtomicBoolean`

2021-10-27 07:05 UTC, fabriziofortino approved these changes

2021-10-27 12:42 UTC, thomasmueller requested changes

2021-10-27 12:42 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/DefaultMemoryManager.java
> +        // todo - should we check and block in the beginning? This creates problem in case of download resume.
Ok, in this case could you remove the TODO and write e.g. "We don't check memory here, as there is no good way here to free up memory in case it is low."?

2021-10-27 12:42 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/DefaultMemoryManager.java
> +                        if (sufficientMemory.get()) {
Hm this not clear... I don't currently see an answer to the question "why you would want to synchronize on it"

2021-10-27 12:42 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +                log.error("{} could not close NodeStateEntryTraverser", taskID);
Could you log the stack trace as well? Just add ", e" to the log.error call.

2021-10-27 12:42 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +        synchronized (this) {
I don't understand the exact use for synchronization... which data structure needs to be protected from concurrent operations?

2021-10-27 12:42 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +        long size = entryBatch.size();
Here we access entryBatch without synchronized - again, I feel it's better to use "save" data structures (e.g. in java.util.concurrent), instead of synchronizing ourselves. If we need to synchronize ourselves, then we need to do it consistently, and write sufficient test cases that verify all possible concurrency problems (which is very hard).

2021-10-27 12:42 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +                NodeStateHolder h = entryBatch.removeFirst();
This is possibly another case of unsynchronized access to entryBatch

2021-11-01 10:49 UTC, averma21 commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/TraverseAndSortTask.java
> +        long size = entryBatch.size();
Removed synchronization.

2021-11-30 15:17 UTC, thomasmueller approved these changes

2021-12-01 07:03 UTC, merged