OAK-9649 - Improve multithreaded download retry strategy during indexing
apache/jackrabbit-oak pull request #450
Opened 2022-01-06 08:41 UTC by averma21

2022-01-11 15:36 UTC, thomasmueller requested changes

2022-01-11 15:36 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/plugins/document/mongo/MongoDocumentTraverser.java
> +                String condition = "{$gt:\"" + startAfterDocumentID + "\"}";
@averma21  and me found out this could skip over some entries.

2022-01-11 15:36 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/MultithreadedTraverseWithSortStrategy.java
> +                            addTask(new TraversingRange(new LastModifiedRange(start, start+1), savedState.id), nodeStateEntryTraverserFactory,
Nit: please add spaces around +

2022-01-11 15:36 UTC, thomasmueller commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/index/indexer/document/flatfile/MultithreadedTraverseWithSortStrategy.java
> +                            if (end != start + 1) {
What about the edge case of "end == start"? It may be impossible in practise, but I wouldn't take any chances and use "if (end > start + 1)" instead.

2022-01-13 12:18 UTC, thomasmueller approved these changes

2022-01-13 12:29 UTC, averma21 commented on oak-run-commons/src/main/java/org/apache/jackrabbit/oak/plugins/document/mongo/MongoDocumentTraverser.java
> +                String condition = "{$gt:\"" + startAfterDocumentID + "\"}";
And, to overcome the problem we create two tasks as mentioned in documentation of MultithreadedTraverseWithSortStrategy :)

2022-01-17 06:30 UTC, merged