OAK-9721: Add state information while indeximporting
apache/jackrabbit-oak pull request #517
Opened 2022-03-11 13:54 UTC by tihom88

2022-03-17 09:25 UTC, thomasmueller requested changes

2022-03-17 09:25 UTC, thomasmueller commented on oak-core/src/main/java/org/apache/jackrabbit/oak/plugins/index/importer/IndexImporter.java
> +    private static final Logger log = LoggerFactory.getLogger(IndexImporter.class);
Nit: if it's static, then in theory (according to the coding rules), "log" should be "LOG". As you anyway have to change the other constants, I recommend to change this as well.

2022-03-17 09:25 UTC, thomasmueller commented on oak-core/src/main/java/org/apache/jackrabbit/oak/plugins/index/importer/IndexImporter.java
> +    public static final String indexImportStateKey = "indexImportState";
but here, I think capitalizing it is the right way: INDEX_IMPORT_STATE_KEY

2022-03-17 09:25 UTC, thomasmueller commented on oak-core/src/main/java/org/apache/jackrabbit/oak/plugins/index/importer/IndexImporter.java
> +    static final int retries = Integer.parseInt(System.getProperty("oak.index.import.retries", "5"));
should be RETRIES

2022-03-17 09:25 UTC, thomasmueller commented on oak-core/src/main/java/org/apache/jackrabbit/oak/plugins/index/importer/IndexImporter.java
> +            try{
Nit: a space after "try" is missing.

2022-03-17 09:25 UTC, thomasmueller commented on oak-core/src/main/java/org/apache/jackrabbit/oak/plugins/index/importer/IndexImporter.java
> +            try{
I think the first thing we should do here is log the error.

2022-03-17 09:25 UTC, thomasmueller commented on oak-core/src/main/java/org/apache/jackrabbit/oak/plugins/index/importer/IndexImporter.java
> +                    log.info("IndexImporterStepExecutor:{} failed after {} retries", indexImportState, maxRetries);
H would use log.warn here.

2022-03-17 09:25 UTC, thomasmueller commented on oak-core/src/main/java/org/apache/jackrabbit/oak/plugins/index/importer/IndexImporter.java
> +                log.info("IndexImporterStepExecutor:{} fail count: {}", indexImportState, count);
I would log.warn here, and also log the exception stack trace (that is, append ", e").

2022-03-17 09:25 UTC, thomasmueller commented on oak-core/src/test/java/org/apache/jackrabbit/oak/plugins/index/importer/IndexImporterTest.java
> +    private String importData_IncrementalUpdate_Before_Setup_Method() throws IOException, CommitFailedException {
That should be importDataIncrementalUpdateBeforeSetup right?

2022-03-17 09:25 UTC, thomasmueller commented on oak-core/src/test/java/org/apache/jackrabbit/oak/plugins/index/importer/IndexImporterTest.java
> +    public void importData_IncrementalUpdate_Test_Failure_AT_SWITCHLANE_State() throws Exception {
This is a mix of camel case, underscore, caps...
importDataIncrementalUpdateTestFailureAtSwitchLaneState

2022-03-17 09:25 UTC, thomasmueller commented on oak-core/src/test/java/org/apache/jackrabbit/oak/plugins/index/importer/IndexImporterTest.java
> +    public void importData_IncrementalUpdate_NO_FAILURE() throws Exception {
importDataIncrementalUpdateNoFailure

2022-03-23 09:07 UTC, tihom88 commented
Raised new PR https://github.com/apache/jackrabbit-oak/pull/527/files. This PR has code conflict with trunk's code.

2022-03-23 09:07 UTC, tihom88 commented
Raised new PR https://github.com/apache/jackrabbit-oak/pull/527/files. This PR has code conflict with trunk's code.

2022-03-23 09:07 UTC, closed without merging