OAK-9741 Test cases for invalid index definitions
apache/jackrabbit-oak pull request #532
Opened 2022-03-30 15:07 UTC by thomasmueller

2022-03-31 00:44 UTC, nit0906 commented
There seems to be compilation errors in the ci builds - 
`[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1735)[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1736)[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1737)[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1738)[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1739)[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1740)[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project oak-lucene: Compilation failure: Compilation failure: 

[ERROR] /home/jenkins/jenkins-agent/workspace/Jackrabbit_oak-trunk-pr_PR-532/oak-lucene/src/test/java/org/apache/jackrabbit/oak/plugins/index/lucene/invalidData/InvalidIndexDefinitionTest.java:[166,61] cannot find symbol

[ERROR]   symbol:   method of(java.lang.String)

[ERROR]   location: interface java.util.List

[ERROR] /home/jenkins/jenkins-agent/workspace/Jackrabbit_oak-trunk-pr_PR-532/oak-lucene/src/test/java/org/apache/jackrabbit/oak/plugins/index/lucene/invalidData/InvalidIndexDefinitionTest.java:[167,61] cannot find symbol

[ERROR]   symbol:   method of(java.lang.String)

[ERROR]   location: interface java.util.List`

2022-03-31 00:49 UTC, nit0906 commented on oak-lucene/src/test/java/org/apache/jackrabbit/oak/plugins/index/lucene/invalidData/InvalidIndexDefinitionTest.java
> +        // 1L + Integer.MAX_VALUE results in IllegalArgumentException: Out of range: 2147483648
Comment can be fixed here to point out the expected behaviour when this value is set to a negative number.

2022-03-31 00:52 UTC, nit0906 commented on oak-lucene/src/test/java/org/apache/jackrabbit/oak/plugins/index/lucene/invalidData/InvalidIndexDefinitionTest.java
> +        // this will commit, but in oak-run it will not work:
Maybe we can add assertions on logs here to check this error is logged properly ? 
Refer LogCustomizer usage here https://github.com/apache/jackrabbit-oak/blob/trunk/oak-core/src/test/java/org/apache/jackrabbit/oak/query/stats/QuerySimilarCostTest.java

2022-03-31 00:53 UTC, nit0906 requested changes
lgtm, just a couple of minor things pointed out.

2022-03-31 14:20 UTC, thomasmueller commented
> There seems to be compilation errors in the ci builds -
> 
> ```
> [](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1735)[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1736)[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1737)[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1738)[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1739)[](https://ci-builds.apache.org/blue/organizations/jenkins/Jackrabbit%2Foak-trunk-pr/detail/PR-532/1/pipeline#step-422-log-1740)[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:testCompile (default-testCompile) on project oak-lucene: Compilation failure: Compilation failure: 
> 
> [ERROR] /home/jenkins/jenkins-agent/workspace/Jackrabbit_oak-trunk-pr_PR-532/oak-lucene/src/test/java/org/apache/jackrabbit/oak/plugins/index/lucene/invalidData/InvalidIndexDefinitionTest.java:[166,61] cannot find symbol
> 
> [ERROR]   symbol:   method of(java.lang.String)
> 
> [ERROR]   location: interface java.util.List
> 
> [ERROR] /home/jenkins/jenkins-agent/workspace/Jackrabbit_oak-trunk-pr_PR-532/oak-lucene/src/test/java/org/apache/jackrabbit/oak/plugins/index/lucene/invalidData/InvalidIndexDefinitionTest.java:[167,61] cannot find symbol
> 
> [ERROR]   symbol:   method of(java.lang.String)
> 
> [ERROR]   location: interface java.util.List
> ```
> 
> But I see that java.util.List is imported - not sure why it fails then though.

Maybe this is only supported in a newer Java version... fixed.

2022-04-01 01:02 UTC, nit0906 approved these changes

2022-04-01 06:59 UTC, merged

2022-04-01 07:35 UTC, mreutegg commented
@thomasmueller there is a test failure: https://ci-builds.apache.org/job/Jackrabbit/job/oak-trunk-pr/job/PR-532/2/testReport/junit/org.apache.jackrabbit.oak.plugins.index.lucene.directory/ChunkedOakDirectoryTest/oak_lucene___writes_CustomBlobSize/?cloudbees-analytics-link=scm-reporting%2Ftests%2Ffailed

I've also seen this reproduce on another environment.

2022-04-01 07:50 UTC, thomasmueller commented
@mreutegg thanks! I'm sorry I didn't see this... Fixed with https://github.com/apache/jackrabbit-oak/commit/92c408ea4ef1f345a028f60d4624666c34d11013