OAK-10031 : purge uncommitted revisions and collisions in batches on …
apache/jackrabbit-oak pull request #796
Opened 2022-12-16 09:05 UTC by rishabhdaim

…boot up

2022-12-16 09:05 UTC, rishabhdaim commented
@mreutegg @stefan-egli could you please review the PR.

2022-12-19 07:47 UTC, mreutegg requested changes

2022-12-19 07:47 UTC, mreutegg commented on oak-store-document/src/main/java/org/apache/jackrabbit/oak/plugins/document/NodeDocument.java
> +        for (List<Entry<Revision, String>> localRevisionsList : partition(localRevisions.entrySet(), batchSize)) {
This partitions the revisions present on the documents, whereas I think the actual number of removed revisions should be partitioned. Depending on how uncommitted revisions appear in `localRevisions`, the proposed code passes `UpdateOp` to `findAndUpdate()` with potentially fewer changes than `batchSize`.

2023-01-05 14:55 UTC, mreutegg approved these changes
Looks good to me now.

2023-01-05 14:57 UTC, merged