OAK-10093 : provided support for SSE Customer Keys for AWS
apache/jackrabbit-oak pull request #960
Opened 2023-06-01 09:32 UTC by rishabhdaim

2023-06-06 05:37 UTC, amit-jain approved these changes
lgtm!

2023-06-15 05:24 UTC, rishabhdaim commented
@amit-jain @anchela @mreutegg could you please review the PR, after the new code changes?

2023-06-15 09:50 UTC, mreutegg requested changes

2023-06-15 09:50 UTC, mreutegg commented on oak-blob-cloud/src/main/java/org/apache/jackrabbit/oak/blob/cloud/s3/S3Constants.java
> +     *  Constant to set SSE_KMS encryption.
I think this comment is wrong.
```suggestion
     *  Constant to set SSE_C encryption.
```

2023-06-15 09:50 UTC, mreutegg commented on oak-blob-cloud/src/main/java/org/apache/jackrabbit/oak/blob/cloud/s3/S3Constants.java
> +     *  Constant to set base64 encoded keyID for SSE_C encryption.
I think keyID is misleading. This is the actual customer key.

2023-06-15 09:50 UTC, mreutegg commented on oak-blob-cloud/src/main/java/org/apache/jackrabbit/oak/blob/cloud/s3/S3Constants.java
> +    public static final String S3_SSE_C_KEYID = "sseCustomerKeyId";
I would rename this.
```suggestion
    public static final String S3_SSE_C_KEY = "sseCustomerKey";
```

2023-06-15 09:59 UTC, mreutegg commented
See also my [comment](https://issues.apache.org/jira/browse/OAK-10093?focusedCommentId=17732971&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17732971) in JIRA about use of customer provided encryption key and direct binary access feature in Oak.

2023-06-20 15:30 UTC, mreutegg approved these changes
Looks good to me.

2023-06-26 15:23 UTC, merged